### ISSUE TITLE
lane_detection_publisher.py

### ISSUE THREAD

**Issue by yihsinma** [Erendrgnl/Carla-Ros-Lane-Keeping-System#4]
(CRLKAS) ma@ma-ROG-Strix:~/Desktop/Carla-Ros-Lane-Keeping-System/src/LaneDetection$ python3 lane_detection_publisher.py 
Traceback (most recent call last):
  File "lane_detection_publisher.py", line 38, in <module>
    from LaneDetection.models import laneNet_class
ModuleNotFoundError: No module named 'LaneDetection'

Why ModuleNotFoundError: No module named 'LaneDetection' ?
Can you tell me how to slove this problem 
Thanks.

**Comment by lkc8426** [comment]
same problem. How did you solve it??

**Comment by yihsinma** [comment]
https://github.com/Erendrgnl/Carla-Ros-Lane-Keeping-System/tree/master/src/LaneDetection
download weights and copy files to models/LaneNet/weights.

**Comment by lkc8426** [comment]
I put weight files but same error occurs..
Can you explain it in more detail?
