### ISSUE TITLE
python3 lane_detection_publisher.py

### ISSUE THREAD

**Issue by yihsinma** [Erendrgnl/Carla-Ros-Lane-Keeping-System#5]
Hello
How to display your gif screen (right)？

**Comment by Erendrgnl** [comment]
Hi, output images publishing as a ros node. You can use Rviz to visualize it. The rviz tool allows real-time visualization of all components of the robotic system —the system of coordinates, moving parts, sensors, camera images — on the 3D stage. https://wiki.ros.org/rviz/DisplayTypes/Camera
